// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf0sgXEeWpcbYCv83jicmnwGQhT4nTlpI',
    appId: '1:645416671755:web:48580d5d026bd06fc7850e',
    messagingSenderId: '645416671755',
    projectId: 'test123-7853c',
    authDomain: 'test123-7853c.firebaseapp.com',
    storageBucket: 'test123-7853c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ7kF0-d-jgX4KvvPzweVfd_xphfmnOFc',
    appId: '1:645416671755:android:5542df8773a83222c7850e',
    messagingSenderId: '645416671755',
    projectId: 'test123-7853c',
    storageBucket: 'test123-7853c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYLb3LHjDwQh_k1uvZM0OkoeQ_75SxZeM',
    appId: '1:645416671755:ios:491b877eea7d0b78c7850e',
    messagingSenderId: '645416671755',
    projectId: 'test123-7853c',
    storageBucket: 'test123-7853c.appspot.com',
    iosClientId: '645416671755-04v3jc3rnfnii57facmmk0vrbqe9b0bl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommrence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYLb3LHjDwQh_k1uvZM0OkoeQ_75SxZeM',
    appId: '1:645416671755:ios:491b877eea7d0b78c7850e',
    messagingSenderId: '645416671755',
    projectId: 'test123-7853c',
    storageBucket: 'test123-7853c.appspot.com',
    iosClientId: '645416671755-04v3jc3rnfnii57facmmk0vrbqe9b0bl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommrence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf0sgXEeWpcbYCv83jicmnwGQhT4nTlpI',
    appId: '1:645416671755:web:1a2829f0a3a4241ac7850e',
    messagingSenderId: '645416671755',
    projectId: 'test123-7853c',
    authDomain: 'test123-7853c.firebaseapp.com',
    storageBucket: 'test123-7853c.appspot.com',
  );
}
