// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsyTiAG-oSTRLytyBkVaiIeJ2i_JuqTUQ',
    appId: '1:813249978198:web:ee90d01bf4c3331c1700f7',
    messagingSenderId: '813249978198',
    projectId: 'tasknote-8d716',
    authDomain: 'tasknote-8d716.firebaseapp.com',
    storageBucket: 'tasknote-8d716.appspot.com',
    measurementId: 'G-FGLRKN3SWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjNn2PU7g74x0z9CPw3yRYkcyTm_iE2qs',
    appId: '1:813249978198:android:2176676fc303a4e61700f7',
    messagingSenderId: '813249978198',
    projectId: 'tasknote-8d716',
    storageBucket: 'tasknote-8d716.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo3c4Jk8Cg7HHmhKgSa5XirGPSiDz3_Dg',
    appId: '1:813249978198:ios:17aa77f0b15a6f891700f7',
    messagingSenderId: '813249978198',
    projectId: 'tasknote-8d716',
    storageBucket: 'tasknote-8d716.appspot.com',
    iosBundleId: 'com.example.tasknotatebeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo3c4Jk8Cg7HHmhKgSa5XirGPSiDz3_Dg',
    appId: '1:813249978198:ios:17aa77f0b15a6f891700f7',
    messagingSenderId: '813249978198',
    projectId: 'tasknote-8d716',
    storageBucket: 'tasknote-8d716.appspot.com',
    iosBundleId: 'com.example.tasknotatebeta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsyTiAG-oSTRLytyBkVaiIeJ2i_JuqTUQ',
    appId: '1:813249978198:web:1f5779a01d92adf21700f7',
    messagingSenderId: '813249978198',
    projectId: 'tasknote-8d716',
    authDomain: 'tasknote-8d716.firebaseapp.com',
    storageBucket: 'tasknote-8d716.appspot.com',
    measurementId: 'G-RZ4B5135V5',
  );
}
