name: schoolmanagement
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  get: ^4.6.6
  http: ^1.2.2
  image_picker: ^1.1.2
  flutter_local_notifications: ^18.0.1
  cloud_firestore: ^5.4.2
  sqflite: ^2.4.1
  shared_preferences: ^2.3.2
  path: ^1.9.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.8.0
  fluttericon: ^2.0.0
  google_sign_in: ^6.2.1
  image_pickers: ^2.0.5+2
  flutter_otp_text_field: ^1.2.0
  intl: ^0.19.0
  dartz: ^0.10.1
  lottie: ^3.1.2
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  image: ^4.3.0
  timelines: ^0.1.0
  signature: ^5.5.0
  timezone: ^0.10.0
  alarm: ^4.1.1
  http_parser: ^4.0.2
  url_launcher: ^6.3.1
  video_player: ^2.9.2
  timeago: ^3.7.0
  timeago_flutter: ^3.7.0
  supabase_flutter: ^2.8.3
  collection: ^1.18.0
  permission_handler: ^11.4.0
  file_picker: ^9.2.0
  table_calendar: ^3.1.3
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Moved to dev_dependencies

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/schoolmanagementicon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/schoolmanagementicon.png"
  android: true
  ios: true
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: NotoKufiArabic
      fonts:
        - asset: assets/fonts/NotoKufiArabic-Regular.ttf